language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - sudo apt-get update
  - sudo apt install r-base

before_script:
  - composer self-update
  - composer install

script:
  - composer ci:test