name: CI Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check out R version
        run: R --version

      - name: Run test suite
        run: composer ci:test

  macOS:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Check out R version
        run: R --version

      - name: Run test suite
        run: composer ci:test
        